# Generated by Django 4.2.3 on 2023-07-19 12:24

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название рецепта', max_length=150, validators=[users.validators.NameValidator()], verbose_name='Название')),
                ('kind', models.CharField(help_text='Вид домашнего животного', max_length=150, validators=[users.validators.NameValidator()], verbose_name='Вид домашнего животного')),
                ('photo', models.ImageField(default=None, help_text='Фото питомца', upload_to='pets/photo', verbose_name='Фото питомца')),
            ],
            options={
                'verbose_name': 'Домашние животное',
                'verbose_name_plural': 'Домашние животные',
                'ordering': ('name',),
            },
        ),
    ]
